# Generated by Django 4.2 on 2023-04-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carta',
            name='elemento',
            field=models.CharField(default='', max_length=100),
        ),
    ]
