# Generated by Django 4.2 on 2023-04-30 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0002_carta_elemento'),
    ]

    operations = [
        migrations.AddField(
            model_name='carta',
            name='ataque',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carta',
            name='defesa',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
